version: '3.8'

services:
  mariadb:
    image: mariadb:11.2
    container_name: payment-gateway-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: payment_gateway
      MYSQL_USER: pguser
      MYSQL_PASSWORD: pgpass1234
      TZ: UTC
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+00:00
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodbtimeout=30"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local

